version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://ub1qkktc34gt3q:pa44f80675b5bfeca4c0d1b9b423b6c37874d556618873228bd4dfc1ec759676d@cb681qjlulc2v0.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d9bvqa1otrq2te
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
