# Generated by Django 5.0.4 on 2024-04-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Navi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navi_arr', to='MR_Mapping_API_app.room')),
                ('dep_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navi_dep', to='MR_Mapping_API_app.room')),
            ],
        ),
    ]
